version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - WEBUI_SECRET_KEY=
    volumes:
      - open-webui:/app/backend/data
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  open-webui:
    driver: local

# Usage:
# docker-compose -f docker-compose.working.yml up -d
#
# Access Open WebUI at: http://localhost:3000
#
# Commands:
# - Start: docker-compose -f docker-compose.working.yml up -d
# - Stop: docker-compose -f docker-compose.working.yml down
# - Logs: docker-compose -f docker-compose.working.yml logs -f
# - Update: docker-compose -f docker-compose.working.yml pull && docker-compose -f docker-compose.working.yml up -d
