
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'open-webui'
    metrics_path: /metrics
    static_configs:
      - targets: ['open-webui:8080']

