#!/bin/bash

# Automated Branch Cleanup Script
# Generated by branch_cleanup_assessment.sh

set -euo pipefail

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

echo "🧹 Branch Cleanup - OpenWebUI Installer"
echo "========================================"

# Safety check
read -p "⚠️  This will DELETE merged branches. Continue? (y/N): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "❌ Cleanup cancelled"
    exit 1
fi

# Create backup
BACKUP_DIR=".branch-analysis/backups/$(date +%Y%m%d_%H%M%S)"
mkdir -p "$BACKUP_DIR"

echo "💾 Creating backup of branch information..."
git branch -r > "$BACKUP_DIR/remote_branches.txt"
git branch > "$BACKUP_DIR/local_branches.txt"

DELETED_COUNT=0
FAILED_COUNT=0
FAILED_BRANCHES=()

# Branches to delete (merged and safe)
BRANCHES_TO_DELETE=(
    "codex/complete-error_handling.sh-script"
    "codex/investigate-empty-openwebui-installer-folder"
)

if [[ ${#BRANCHES_TO_DELETE[@]} -eq 0 ]]; then
    echo "ℹ️  No branches to delete - all branches are either unmerged or not safe to delete"
    echo ""
    echo -e "${BLUE}💾 Backup saved to: $BACKUP_DIR${NC}"
    echo -e "${YELLOW}🎉 No cleanup needed!${NC}"
    exit 0
fi

echo "🗑️  Deleting merged branches..."
for branch in "${BRANCHES_TO_DELETE[@]}"; do
    echo "Deleting: $branch"

    # Delete remote branch
    if git push origin --delete "$branch" 2>/dev/null; then
        echo -e "${GREEN}✅ Deleted remote: $branch${NC}"
        DELETED_COUNT=$((DELETED_COUNT + 1))
    else
        echo -e "${RED}❌ Failed to delete remote: $branch${NC}"
        FAILED_COUNT=$((FAILED_COUNT + 1))
        FAILED_BRANCHES+=("$branch")
    fi

    # Delete local branch if it exists
    if git show-ref --verify --quiet "refs/heads/$branch" 2>/dev/null; then
        if git branch -D "$branch" 2>/dev/null; then
            echo -e "${GREEN}✅ Deleted local: $branch${NC}"
        else
            echo -e "${YELLOW}⚠️  Could not delete local: $branch${NC}"
        fi
    fi
done

echo ""
echo "📊 Cleanup Summary:"
echo "=================="
echo -e "✅ Successfully deleted: ${GREEN}$DELETED_COUNT${NC}"
echo -e "❌ Failed to delete: ${RED}$FAILED_COUNT${NC}"

if [[ ${#FAILED_BRANCHES[@]} -gt 0 ]]; then
    echo ""
    echo "Failed branches:"
    for branch in "${FAILED_BRANCHES[@]}"; do
        echo "  - $branch"
    done
fi

echo ""
echo -e "${BLUE}💾 Backup saved to: $BACKUP_DIR${NC}"
echo -e "${GREEN}🎉 Branch cleanup complete!${NC}"
