{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  annotations:
{{ toYaml .Values.secret.annotations | indent 4 }}
stringData:
{{ toYaml .Values.secret.data | indent 2 }}
{{- end }}
