name: Auto PR Merge

on:
  push:
    branches:
      - develop
      - 'phase-*'

jobs:
  auto-pr:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
      statuses: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup GitHub CLI
        uses: cli/cli@v2

      - name: Create pull request if needed
        id: ensure_pr
        env:
          GH_TOKEN: ${{ secrets.GH_AUTOMATION_TOKEN }}
        run: |
          BRANCH="${GITHUB_REF#refs/heads/}"
          PR_NUMBER=$(gh pr list --head "$BRANCH" --json number --jq '.[0].number')
          if [ -z "$PR_NUMBER" ]; then
            gh pr create --fill --base main --head "$BRANCH"
            PR_NUMBER=$(gh pr list --head "$BRANCH" --json number --jq '.[0].number')
          fi
          echo "number=$PR_NUMBER" >> "$GITHUB_OUTPUT"

      - name: Wait for checks to pass
        env:
          GH_TOKEN: ${{ secrets.GH_AUTOMATION_TOKEN }}
        run: gh pr checks "${{ steps.ensure_pr.outputs.number }}" --watch

      - name: Enable auto-merge
        env:
          GH_TOKEN: ${{ secrets.GH_AUTOMATION_TOKEN }}
        run: gh pr merge "${{ steps.ensure_pr.outputs.number }}" --auto --delete-branch

