name: Auto PR

on:
  push:
    branches:
      - develop
      - 'phase-*'

jobs:
  auto-pr:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
      statuses: read

    steps:
      - uses: actions/checkout@v4

      - name: Create pull request if needed
        id: ensure_pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_AUTOMATION_TOKEN || secrets.GH_PR_TOKEN || secrets.GITHUB_TOKEN }}
          script: |
            const branch = context.ref.replace('refs/heads/', '');
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            const { data: prs } = await github.rest.pulls.list({
              owner,
              repo,
              state: 'open',
              head: `${owner}:${branch}`,
              base: 'main'
            });
            let pr;
            if (prs.length > 0) {
              pr = prs[0];
              core.notice(`Found existing PR #${pr.number}`);
            } else {
              pr = (await github.rest.pulls.create({
                owner,
                repo,
                head: branch,
                base: 'main',
                title: `Merge ${branch} into main`,
                body: 'Automated PR from workflow.'
              })).data;
              core.notice(`Created PR #${pr.number}`);
            }
            core.setOutput('number', pr.number.toString());
            core.setOutput('url', pr.html_url);

      - name: Wait for checks to pass
        env:
          GH_TOKEN: ${{ secrets.GH_AUTOMATION_TOKEN || secrets.GH_PR_TOKEN || secrets.GITHUB_TOKEN }}
        run: |
          gh pr checks "${{ steps.ensure_pr.outputs.url }}" --watch

      - name: Merge and delete branch
        env:
          GH_TOKEN: ${{ secrets.GH_AUTOMATION_TOKEN || secrets.GH_PR_TOKEN || secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge "${{ steps.ensure_pr.outputs.url }}" --squash --delete-branch
