name: Tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          if [ -d wheelhouse ] && [ -f requirements-dev-no-github.txt ]; then
            pip install --no-index --find-links=wheelhouse -r requirements-dev-no-github.txt
          else
            pip install -r requirements-dev.txt
          fi
      - name: Run tests
        run: pytest -q
